
clc;
clear;
close all;
%基本处理
filename='./data/man_voice.wav';
[y,Fs] = audioread(filename);%读取语音信号
[f,P1]=unilateral_fft(y,Fs);%自定义函数求语音信号单边谱
figure();
subplot(2,1,1);
plot([0:length(y)-1]/Fs,y);
xlabel('t(s)');
ylabel('y(t)');
title('原语音信号波形');
subplot(2,1,2);
plot(f,P1);
xlabel('f(Hz)');
ylabel('|P1(f)|');
title('原语音信号单边频谱');

%低通滤波器设计
fp=1e3;fs=1.2e3;
As=100;Ap=1;
wp=fp/Fs*2*pi;
ws=fs/Fs*2*pi;
[n1,wn1]=ellipord(wp/pi,ws/pi,Ap,As);%使用椭圆滤波器设计低通滤波器
[bd1,ad1]=ellip(n1,Ap,As,wn1);%直接法设计数字低通滤波器
[H1,w1]=freqz(bd1,ad1,1024);
dbH1=20*log10(abs(H1)/max(abs(H1)));
figure();
subplot(2,1,1);
plot(w1/(2*pi)*Fs,dbH1);
xlabel('f/Hz');
ylabel('dB');
title('低通数字滤波器相对频率特性');
axis([0,2000,-120,0]);
set(gca,'Xtick',[fp,fs]);
set(gca,'Ytick',[-As,-Ap]);grid
subplot(2,1,2);
plot(w1/(2*pi)*Fs,angle(H1)/pi*180)
xlabel('f/Hz');
ylabel('\phi');
title('低通数字滤波器相位特性');
y1=filter(bd1,ad1,y);%y1为低通数字滤波器滤波后语音信号
figure();
subplot(2,1,1);
plot([0:length(y1)-1]/Fs,y1);
xlabel('t(s)');
ylabel('y1(t)');
title('低通数字滤波器滤波后语音信号波形');
subplot(2,1,2);
[f1,P11]=unilateral_fft(y1,Fs);
plot(f1,P11);
xlabel('f(Hz)');
ylabel('|P1(f)|');
title('低通数字滤波器滤波后语音信号单边频谱');

%高通滤波器设计
fp=5000;fs=4800;
Ap=1;As=100;
wp=fp/Fs*2*pi;
ws=fs/Fs*2*pi;
[n2,wn2]=ellipord(wp/pi,ws/pi,Ap,As);%使用椭圆滤波器设计高通滤波器
[bd2,ad2]=ellip(n2,Ap,As,wn2,'high');%直接法设计数字高通滤波器
[H2,w2]=freqz(bd2,ad2,1024);
dbH2=20*log10(abs(H2)/max(abs(H2)));
figure();
subplot(2,1,1);
plot(w2/(2*pi)*Fs,dbH2);
xlabel('f/Hz');
ylabel('dB');
title('高通数字滤波器相对频率特性');
axis([0,6000,-120,0]);
set(gca,'Xtick',[fs,fp]);
set(gca,'Ytick',[-As,-Ap]);grid
subplot(2,1,2);
plot(w2/(2*pi)*Fs,angle(H2)/pi*180)
xlabel('f/Hz');
ylabel('\phi');
title('高通数字滤波器相位特性');
y2=filter(bd2,ad2,y);%y2为高通数字滤波器滤波后语音信号
figure();
subplot(2,1,1);
plot([0:length(y2)-1]/Fs,y2);
xlabel('t(s)');
ylabel('y2(t)');
title('高通数字滤波器滤波后语音信号波形');
subplot(2,1,2);
[f2,P12]=unilateral_fft(y2,Fs);
plot(f2,P12);
xlabel('f(Hz)');
ylabel('|P1(f)|');
title('高通数字滤波器滤波后语音信号单边频谱');

%带通滤波器设计
fpl=1200;fpu=3000;fsl=1000;fsu=3200;
wp=[2*fpl/Fs,2*fpu/Fs]*pi;ws=[2*fsl/Fs,2*fsu/Fs]*pi;
Ap=1;As=100;
deltaw=wp(1)-ws(1);
N0=ceil(35*pi/deltaw);
NN=N0+mod(N0+1,2);%使用窗函数法设计带通滤波器
windows=(blackman(NN));%使用blackman窗
wc1=(ws(1)+wp(1))/2/pi;
wc2=(ws(2)+wp(2))/2/pi;
bd3=fir1(NN-1,[wc1,wc2],windows);
ad3=1;
[H3,w3]=freqz(bd3,ad3,1024);
dbH3=20*log10(abs(H3)/max(abs(H3)));
figure();
subplot(2,1,1);
plot(w3/(2*pi)*Fs,dbH3);
xlabel('f/Hz');
ylabel('dB');
title('带通数字滤波器相对频率特性');
axis([0,4000,-120,0]);
set(gca,'Xtick',[fsl,fpl,fpu,fsu]);
set(gca,'Ytick',[-As,-Ap]);grid
subplot(2,1,2);
plot(w3/(2*pi)*Fs,angle(H3)/pi*180)
xlabel('f/Hz');
ylabel('\phi');
title('带通数字滤波器相位特性');
y3=filter(bd3,ad3,y);%y2为带通数字滤波器滤波后语音信号
figure();
subplot(2,1,1);
plot([0:length(y3)-1]/Fs,y3);
xlabel('t(s)');
ylabel('y3(t)');
title('带通数字滤波器滤波后语音信号波形');
subplot(2,1,2);
[f3,P13]=unilateral_fft(y3,Fs);
plot(f3,P13);
xlabel('f(Hz)');
ylabel('|P1(f)|');
title('带通数字滤波器滤波后语音信号单边频谱');


%变为女声和童声
filename_woman='./data/woman_voice.wav';%女声
filename_child='./data/child_voice.wav';%童声
y_woman=shiftPitch(y,4);
y_child=shiftPitch(y,7);
audiowrite(filename_woman,y_woman,Fs);
audiowrite(filename_child,y_child,Fs);

[f,P1_woman]=unilateral_fft(y_woman,Fs);%自定义函数求语音信号单边谱
figure();
subplot(2,1,1);
plot([0:length(y_woman)-1]/Fs,y_woman);
xlabel('t(s)');
ylabel('ywoman(t)');
title('男声转换为女声后语音信号波形');
subplot(2,1,2);
plot(f,P1_woman);
xlabel('f(Hz)');
ylabel('|P1woman(f)|');
title('男声转换为女声后语音信号单边频谱');

